name: Build and push DB

on:
  push:
    branches: [ "main" ]
    paths: ['pipelines/**']

jobs:
  build_and_push_db:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: uv sync

      - name: Build DB
        run: uv run pipelines/run.py run build_database

      - name: Upload DB to S3
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
        run: uv run pipelines/run.py run push_database_to_s3
        